services:
  - type: web
    name: smellpin-backend
    env: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: smellpin-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: smellpin-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false

databases:
  - name: smellpin-db
    databaseName: smellpin
    user: smellpin
    region: oregon
    plan: starter

  - type: redis
    name: smellpin-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru