groups:
  - name: smellpin.system
    rules:
      # 服务宕机告警
      - alert: ServiceDown
        expr: up{job="smellpin-api"} == 0
        for: 1m
        labels:
          severity: critical
          service: smellpin-api
        annotations:
          summary: "SmellPin API 服务宕机"
          description: "SmellPin API 服务已宕机超过 1 分钟"

      # 高错误率告警
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total[5m]))
          ) * 100 > 5
        for: 5m
        labels:
          severity: warning
          service: smellpin-api
        annotations:
          summary: "API 错误率过高"
          description: "API 错误率超过 5%，当前值: {{ $value }}%"

      # 响应时间过慢告警
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 10m
        labels:
          severity: warning
          service: smellpin-api
        annotations:
          summary: "API 响应时间过慢"
          description: "API P95 响应时间超过 1 秒，当前值: {{ $value }}s"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: |
          (process_resident_memory_bytes / 1024 / 1024 / 1024) > 1
        for: 5m
        labels:
          severity: warning
          service: smellpin-api
        annotations:
          summary: "内存使用率过高"
          description: "应用内存使用超过 1GB，当前值: {{ $value }}GB"

      # CPU 使用率过高
      - alert: HighCPUUsage
        expr: |
          rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: smellpin-api
        annotations:
          summary: "CPU 使用率过高"
          description: "应用 CPU 使用率超过 80%，当前值: {{ $value }}%"

  - name: smellpin.database
    rules:
      # 数据库连接失败
      - alert: DatabaseConnectionFailed
        expr: database_connections_active == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "数据库连接失败"
          description: "数据库连接池中没有活跃连接"

      # 数据库连接数过高
      - alert: HighDatabaseConnections
        expr: database_connections_active > 50
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "数据库连接数过高"
          description: "数据库活跃连接数超过 50，当前值: {{ $value }}"

  - name: smellpin.redis
    rules:
      # Redis 连接失败
      - alert: RedisConnectionFailed
        expr: redis_connections_active == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis 连接失败"
          description: "Redis 连接池中没有活跃连接"

      # Redis 内存使用率过高
      - alert: HighRedisMemoryUsage
        expr: |
          (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis 内存使用率过高"
          description: "Redis 内存使用率超过 80%，当前值: {{ $value }}%"

  - name: smellpin.business
    rules:
      # 用户注册数骤降
      - alert: LowUserRegistration
        expr: |
          sum(rate(users_registered_total[1h])) < 1
        for: 2h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "用户注册数异常低"
          description: "过去 2 小时用户注册数低于正常水平，当前每小时注册数: {{ $value }}"

      # 支付失败率过高
      - alert: HighPaymentFailureRate
        expr: |
          (
            sum(rate(payments_failed_total[5m]))
            /
            sum(rate(payments_total[5m]))
          ) * 100 > 10
        for: 10m
        labels:
          severity: warning
          service: payment
        annotations:
          summary: "支付失败率过高"
          description: "支付失败率超过 10%，当前值: {{ $value }}%"

      # 标注创建数异常低
      - alert: LowAnnotationCreation
        expr: |
          sum(rate(annotations_created_total[1h])) < 5
        for: 2h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "标注创建数异常低"
          description: "过去 2 小时标注创建数低于正常水平，当前每小时创建数: {{ $value }}"

      # LBS 奖励发放异常
      - alert: LBSRewardDistributionIssue
        expr: |
          sum(rate(lbs_rewards_distributed_total[1h])) == 0
        for: 1h
        labels:
          severity: warning
          service: lbs
        annotations:
          summary: "LBS 奖励发放异常"
          description: "过去 1 小时没有 LBS 奖励发放记录"

  - name: smellpin.security
    rules:
      # 可疑登录尝试
      - alert: SuspiciousLoginAttempts
        expr: |
          sum(rate(login_attempts_failed_total[5m])) > 10
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "可疑登录尝试"
          description: "过去 5 分钟失败登录尝试超过 10 次，当前值: {{ $value }}"

      # 限流触发过多
      - alert: HighRateLimitHits
        expr: |
          sum(rate(rate_limit_hits_total[5m])) > 100
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "限流触发过多"
          description: "过去 5 分钟限流触发超过 100 次，当前值: {{ $value }}"

  - name: smellpin.websocket
    rules:
      # WebSocket 连接数异常
      - alert: WebSocketConnectionIssue
        expr: |
          websocket_connections < 10 or websocket_connections > 10000
        for: 10m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "WebSocket 连接数异常"
          description: "WebSocket 连接数异常，当前值: {{ $value }}"