# Prometheus 告警规则配置
groups:
  # 系统级别告警
  - name: system_alerts
    rules:
      # CPU 使用率过高
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "CPU 使用率过高"
          description: "实例 {{ $labels.instance }} CPU 使用率为 {{ $value }}%，超过 80% 阈值"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "内存使用率过高"
          description: "实例 {{ $labels.instance }} 内存使用率为 {{ $value }}%，超过 85% 阈值"

      # 磁盘空间不足
      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 5m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "磁盘空间不足"
          description: "实例 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率为 {{ $value }}%，超过 90% 阈值"

  # 应用级别告警
  - name: application_alerts
    rules:
      # 应用服务不可用
      - alert: ApplicationDown
        expr: up{job="smellpin-backend"} == 0
        for: 1m
        labels:
          severity: critical
          category: application
        annotations:
          summary: "应用服务不可用"
          description: "SmellPin 后端服务 {{ $labels.instance }} 已停止响应"

      # HTTP 错误率过高
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "HTTP 错误率过高"
          description: "HTTP 5xx 错误率为 {{ $value }}%，超过 5% 阈值"

      # API 响应时间过长
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "API 响应时间过长"
          description: "95% 的请求响应时间超过 500ms，当前为 {{ $value }}s"

      # 请求量异常下降
      - alert: LowRequestRate
        expr: rate(http_requests_total[5m]) < 1
        for: 10m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "请求量异常下降"
          description: "每秒请求数降至 {{ $value }}，可能存在问题"

  # 数据库告警
  - name: database_alerts
    rules:
      # PostgreSQL 连接数过高
      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "PostgreSQL 连接数过高"
          description: "PostgreSQL 连接数使用率为 {{ $value }}%，超过 80% 阈值"

      # PostgreSQL 查询时间过长
      - alert: PostgreSQLSlowQueries
        expr: pg_stat_activity_max_tx_duration > 300
        for: 2m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "PostgreSQL 查询时间过长"
          description: "存在运行超过 5 分钟的查询，当前最长查询时间为 {{ $value }}s"

      # Redis 内存使用率过高
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "Redis 内存使用率过高"
          description: "Redis 内存使用率为 {{ $value }}%，超过 90% 阈值"

      # Redis 连接数过高
      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "Redis 连接数过高"
          description: "Redis 当前连接数为 {{ $value }}，超过 100 个连接"

  # 业务指标告警
  - name: business_alerts
    rules:
      # 用户注册量异常下降
      - alert: LowUserRegistration
        expr: increase(user_registrations_total[1h]) < 5
        for: 2h
        labels:
          severity: warning
          category: business
        annotations:
          summary: "用户注册量异常下降"
          description: "过去 1 小时用户注册量仅为 {{ $value }}，低于正常水平"

      # 支付失败率过高
      - alert: HighPaymentFailureRate
        expr: rate(payment_failures_total[5m]) / rate(payment_attempts_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: critical
          category: business
        annotations:
          summary: "支付失败率过高"
          description: "支付失败率为 {{ $value }}%，超过 10% 阈值"

      # 标注创建量异常
      - alert: AbnormalAnnotationCreation
        expr: abs(rate(annotations_created_total[1h]) - rate(annotations_created_total[1h] offset 24h)) / rate(annotations_created_total[1h] offset 24h) * 100 > 50
        for: 1h
        labels:
          severity: warning
          category: business
        annotations:
          summary: "标注创建量异常"
          description: "标注创建量与昨日同期相比变化 {{ $value }}%，超过 50% 阈值"

      # LBS 奖励发放异常
      - alert: LBSRewardAbnormal
        expr: rate(lbs_rewards_distributed_total[5m]) == 0 and rate(lbs_discoveries_total[5m]) > 0
        for: 10m
        labels:
          severity: critical
          category: business
        annotations:
          summary: "LBS 奖励发放异常"
          description: "检测到 LBS 发现但未发放奖励，可能存在系统问题"

  # 安全告警
  - name: security_alerts
    rules:
      # 异常登录尝试
      - alert: HighFailedLoginAttempts
        expr: rate(auth_failed_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "异常登录尝试"
          description: "检测到高频登录失败，每秒失败次数为 {{ $value }}"

      # API 限流触发
      - alert: RateLimitTriggered
        expr: rate(rate_limit_exceeded_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "API 限流频繁触发"
          description: "API 限流每秒触发 {{ $value }} 次，可能存在恶意请求"

      # 可疑的地理位置访问
      - alert: SuspiciousGeoLocation
        expr: rate(suspicious_geo_access_total[5m]) > 1
        for: 5m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "检测到可疑地理位置访问"
          description: "检测到来自可疑地理位置的访问，每秒 {{ $value }} 次"

  # 网络告警
  - name: network_alerts
    rules:
      # 网络延迟过高
      - alert: HighNetworkLatency
        expr: probe_duration_seconds > 1
        for: 5m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "网络延迟过高"
          description: "网络探测延迟为 {{ $value }}s，超过 1s 阈值"

      # SSL 证书即将过期
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1h
        labels:
          severity: warning
          category: network
        annotations:
          summary: "SSL 证书即将过期"
          description: "SSL 证书将在 {{ $value | humanizeDuration }} 后过期"