# Prometheus 配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smellpin-production'
    environment: 'production'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node.js 应用监控
  - job_name: 'smellpin-backend'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Nginx 监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 10s
    metrics_path: /metrics

  # PostgreSQL 监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s
    metrics_path: /metrics

  # Redis 监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    metrics_path: /metrics

  # Node Exporter (系统监控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # cAdvisor (容器监控)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  # 自定义业务指标
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics/business
    honor_labels: true

  # 健康检查监控
  - job_name: 'health-checks'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /health/metrics
    honor_labels: true

  # API 性能监控
  - job_name: 'api-performance'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /api/metrics/performance
    honor_labels: true

  # 用户行为监控
  - job_name: 'user-behavior'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/user-behavior
    honor_labels: true

  # 支付系统监控
  - job_name: 'payment-metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics/payment
    honor_labels: true

  # LBS 系统监控
  - job_name: 'lbs-metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics/lbs
    honor_labels: true

# 远程写入配置 (可选，用于长期存储)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# 远程读取配置 (可选)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"